### PR TITLE
Adding Blocks and Load and Analyze Workshop update (WMS 141 and WMS 8081)

### PR DESCRIPTION
**Pull request by martygubar**
This pull requests introduces building blocks - which will simplify workshop development. It also has the start to Load and Analyze ADB workshop that will be used for Cloud World. These updates have no impact on external facing workshops yet. They are all additive.

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Make sure all images’ filenames are lower case
2. Images’ names should be descriptive
3. Use the [oracle-livelabs.github.io](http://oracle-livelabs.github.io/) links in manifest.json and index.html, instead of learning-library links. Refer to these files for examples: https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops/tenancy 
4. Include workshop’s WMS in the title of the PR
Thank you!

**Comment by martygubar** [comment]
workshop ID 141

Images are fixed. Titles fixed. Blocks updated. We should be all set!

Thanks Arabella!

**Comment by madhusudhanrao-ppm** [comment]
Picture100-*.png should be all lower case, 

please check index.html to be pointing to oracle-livelabs/ repo instead of learning-library/ repo

Please rename .sql files to have hyphen - instead of _ underscore, following the QA naming conventions. 

https://oracle-livelabs.github.io/common/redwood-hol/js/jquery-1.11.0.min.js
https://oracle-livelabs.github.io/common/redwood-hol/js/jquery-ui-1.10.4.custom.js
https://oracle-livelabs.github.io/common/redwood-hol/js/main.min.js 
https://oracle-livelabs.github.io/common/redwood-hol/css/style.min.css
https://oracle-livelabs.github.io/common/redwood-hol/img/favicon.ico

**Comment by martygubar** [comment]
These updates are for:
WMS 141 : Load and Analyze Your Data with Autonomous Database 
WMS 8081: Integrate, Analyze and Act on All data using Autonomous Database

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues with your PR:
1. In building-blocks/setup/images, "Picture100..." should be all lowercase;
2. In building-blocks/setup/scripts, please use dashes instead of underscores for filenames, the same goes for building-blocks/setup/workshop_package.sql
3. building-blocks/workshops/freetier/index.html should contain oracle-live labs.github.io link instead of learning-library links
4. Change movie-stream-story-lite/add-data-scripts/lab_setup.sql to use dash instead of underscore
Thanks!

**Comment by martygubar** [comment]
Filename updates are in.
WMS 141 : Load and Analyze Your Data with Autonomous Database
WMS 8081: Integrate, Analyze and Act on All data using Autonomous Database

**Review by arabellayao — COMMENTED** [review]
Hi! In building-blocks/setup/scripts, please use dashes instead of underscores for filenames. Thanks!

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
