### PR TITLE
Tejus

### PR DESCRIPTION
**Pull request by tejuscs**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by ramumg** [comment]
Hi @tejuscs, 

can you please provide the WMS ID for this workshop?

Thank you, 
Ramu

**Comment by tejuscs** [comment]
WMS ID: 11048

**Review by ramumg — CHANGES_REQUESTED** [review]
Hi @tejuscs,
All your files names should be lowercase and using "-" instead of "_"
image
for example: create-audf-new.png

There are some labs that do not have steps numbers under the tasks for example adb-provision-autonomous  
Your tasks should look like this: 
image

Let me know if you have any questions. 

Thank you, 
Ramu

**Comment by tejuscs** [comment]
@ramumg changed it to lowercase and removed "_". We have an announcement going to happen today for tls certs (New lab added). Can you please approve the pull request?

**Review by ramumg — DISMISSED** [review]

**Review by ramumg — APPROVED** [review]

**Pull request merged**
