### PR TITLE
WMS #11071 - Updating some minor typos

### PR DESCRIPTION
**Pull request by silversurfer63**
WMS #11071 

Updates typographical errors on a number of pages.  Which include adding an escape character before an _ and , updating links, etc.

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! What is your oracle email? I need to confirm if you are a workshop team member. Thank you!

**Comment by silversurfer63** [comment]
***@***.***
________________________________
From: Arabella Yao ***@***.***>
Sent: Tuesday, September 20, 2022 2:15 PM
To: oracle-livelabs/adb ***@***.***>
Cc: Larry Fumagalli ***@***.***>; Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/adb] WMS #11071 - Updating some minor typos (PR #50)


@arabellayao requested changes on this pull request.

Hi! What is your oracle email? I need to confirm if you are a workshop team member. Thank you!

**Comment by arabellayao** [comment]
You email is masked. Please talk to @arabellayao (@aryao on Slack). Thanks!

**Comment by silversurfer63** [comment]
Arabella,

  Just sent you a slack.

Thanks,

  Larry
________________________________
From: Arabella Yao ***@***.***>
Sent: Tuesday, September 20, 2022 2:21 PM
To: oracle-livelabs/adb ***@***.***>
Cc: Larry Fumagalli ***@***.***>; Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/adb] WMS #11071 - Updating some minor typos (PR #50)


You email is masked. Please talk to @arabellayao<https://urldefense.com/v3/__https://github.com/arabellayao__;!!ACWV5N9M2RV99hQ!JoU3P5AKdFnolGIx0xTEGRsKvcDvTRtktvVrIg4D4kv-IgIbsjcnpCJ6qt6gFywOKCzWRLPFyQJHq0yHo_g7aD8glei_2Q$> ***@***.***<https://urldefense.com/v3/__https://github.com/Aryao__;!!ACWV5N9M2RV99hQ!JoU3P5AKdFnolGIx0xTEGRsKvcDvTRtktvVrIg4D4kv-IgIbsjcnpCJ6qt6gFywOKCzWRLPFyQJHq0yHo_g7aD-f-MRSJA$> on Slack). Thanks!

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
