### PR TITLE
WMS 11071 - Added a New Workshop for OCW

### PR DESCRIPTION
**Pull request by silversurfer63**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by anooshapilli** [comment]
@silversurfer63 - Just wanted to confirm if you are listed on the workshop team for WMS ID 11071? If yes, could you share your name?

**Comment by anooshapilli** [comment]
@silversurfer63 - There are a few changes that need to be made to the workshop. Please check the Self QA Checklist in WMS to  or check this guide to perform the Self QA of the workshop - [LINK](https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/livelabs/?lab=5-labs-qa-checks#Task3:SelfQA)
Reference sample workshop - [LINK](https://oracle-livelabs.github.io/common/sample-livelabs-templates/sample-workshop/workshops/tenancy/)

**Comment by silversurfer63** [comment]
Larry Fumagalli.. Sorry
________________________________
From: Anoosha Pilli ***@***.***>
Sent: Friday, August 18, 2023 12:44 PM
To: oracle-livelabs/adb ***@***.***>
Cc: Larry Fumagalli ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/adb] WMS 11071 - Added a New Workshop for OCW (PR #228)


@silversurfer63<https://urldefense.com/v3/__https://github.com/silversurfer63__;!!ACWV5N9M2RV99hQ!P43iORWAwLO41VPPR_gH68LkHPYJVkSLWtfsFtv5zjt5hQDx5QZmeSs1owC1jmpIvN_RHb2MQP471iZxcELBoeNhy2aB4w$> - Just wanted to confirm if you are listed on the workshop team for WMS ID 11071? If yes, could you share your name?

**Comment by silversurfer63** [comment]
Anoosha,

I am just adding a new workshop to the existing workshop..  I added the new manifest and such and then the corresponding folders..

What am I missing??

Thanks,

  Larry
________________________________
From: Anoosha Pilli ***@***.***>
Sent: Friday, August 18, 2023 12:47 PM
To: oracle-livelabs/adb ***@***.***>
Cc: Larry Fumagalli ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/adb] WMS 11071 - Added a New Workshop for OCW (PR #228)


@silversurfer63<https://urldefense.com/v3/__https://github.com/silversurfer63__;!!ACWV5N9M2RV99hQ!JDpCx9XHE5sL41wBaQXiAg0A0IRlLIgYdw1Fz30zKEi09lHcMT_VdduMoyzRUr9Xl50sN6mBlC_JUibuhJVV23579bkSTA$> - There are a few changes that need to be made to the workshop. Please check the Self QA Checklist in WMS to or check this guide to perform the Self QA of the workshop - LINK<https://urldefense.com/v3/__https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/livelabs/?lab=5-labs-qa-checks*Task3:SelfQA__;Iw!!ACWV5N9M2RV99hQ!JDpCx9XHE5sL41wBaQXiAg0A0IRlLIgYdw1Fz30zKEi09lHcMT_VdduMoyzRUr9Xl50sN6mBlC_JUibuhJVV234vjtFsGA$>
Reference sample workshop - LINK<https://urldefense.com/v3/__https://oracle-livelabs.github.io/common/sample-livelabs-templates/sample-workshop/workshops/tenancy/__;!!ACWV5N9M2RV99hQ!JDpCx9XHE5sL41wBaQXiAg0A0IRlLIgYdw1Fz30zKEi09lHcMT_VdduMoyzRUr9Xl50sN6mBlC_JUibuhJVV237BQDO-zg$>

**Comment by silversurfer63** [comment]
Anoosha,

 I have updated, can you please try the pull again.

Thanks,

  Larry
________________________________
From: Anoosha Pilli ***@***.***>
Sent: Friday, August 18, 2023 12:47 PM
To: oracle-livelabs/adb ***@***.***>
Cc: Larry Fumagalli ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/adb] WMS 11071 - Added a New Workshop for OCW (PR #228)


@silversurfer63<https://urldefense.com/v3/__https://github.com/silversurfer63__;!!ACWV5N9M2RV99hQ!JDpCx9XHE5sL41wBaQXiAg0A0IRlLIgYdw1Fz30zKEi09lHcMT_VdduMoyzRUr9Xl50sN6mBlC_JUibuhJVV23579bkSTA$> - There are a few changes that need to be made to the workshop. Please check the Self QA Checklist in WMS to or check this guide to perform the Self QA of the workshop - LINK<https://urldefense.com/v3/__https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/livelabs/?lab=5-labs-qa-checks*Task3:SelfQA__;Iw!!ACWV5N9M2RV99hQ!JDpCx9XHE5sL41wBaQXiAg0A0IRlLIgYdw1Fz30zKEi09lHcMT_VdduMoyzRUr9Xl50sN6mBlC_JUibuhJVV234vjtFsGA$>
Reference sample workshop - LINK<https://urldefense.com/v3/__https://oracle-livelabs.github.io/common/sample-livelabs-templates/sample-workshop/workshops/tenancy/__;!!ACWV5N9M2RV99hQ!JDpCx9XHE5sL41wBaQXiAg0A0IRlLIgYdw1Fz30zKEi09lHcMT_VdduMoyzRUr9Xl50sN6mBlC_JUibuhJVV237BQDO-zg$>

**Comment by silversurfer63** [comment]
Due to be approved last week and this is a vendor run lab, I did not have time to cut and paste all steps..  So the only task will be to download the PDF associated to each lab (link in each lab) and use that to go through all of the task

David Start mentioned doing this

**Comment by silversurfer63** [comment]
This lab is only for OCW Event

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
