### PR TITLE
WMS ID: 5961 + 11009 changes for local Mongo tools install

### PR DESCRIPTION
**Pull request by RogerFord**

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please include the workshop's WMS ID (instead of production ID) in the PR's title.

**Comment by RogerFord** [comment]
My mistake. WMS ID is 831. Please don't tell me I need to create a whole new PR in order to get this info in the title?

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi Roger! You only need to edit the PR's title to add the WMS ID. However, I was not able to find #831 in WMS. Could you please confirm the WMS ID and also let me know the workshop title?Thank you!

**Review by arabellayao — COMMENTED** [review]
Hi! Is the folder "mongodb-api" part of the workshop #5961? Thanks!

**Comment by RogerFord** [comment]
There are workshops under adb/json that I’m responsible for:

5961 which in folder json-soda-ajd
11009 which is in folder mongodb-api

I may have lost track of which one this PR is for.

Roger


From: Arabella Yao ***@***.***>
Date: Tuesday, 26 July 2022 at 19:43
To: oracle-livelabs/adb ***@***.***>
Cc: Roger Ford ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/adb] WMS ID: 5961 changes for local Mongo tools install (PR #16)

@arabellayao commented on this pull request.

Hi! Is the folder "mongodb-api" part of the workshop #5961? Thanks!

**Comment by RogerFord** [comment]
It appears to be 5961: Developing with JSON and SODA in Oracle Database
https://apex.oraclecorp.com/pls/apex/f?p=24885:320:105424198127480::::P320_ID:5961

Now updated in the title.

Roger

From: Arabella Yao ***@***.***>
Date: Tuesday, 26 July 2022 at 04:35
To: oracle-livelabs/adb ***@***.***>
Cc: Roger Ford ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/adb] #831 changes for local Mongo tools install (PR #16)

@arabellayao requested changes on this pull request.

Hi Roger! You only need to edit the PR's title to add the WMS ID. However, I was not able to find #831 in WMS. Could you please confirm the WMS ID and also let me know the workshop title?Thank you!

**Pull request merged**
