### PR TITLE
Workshop ID#142 Added callouts to 2 screenshots in Lab 13: Public and Private Network Access in Autonomous Database 

### PR DESCRIPTION
**Pull request by greenrick**
Workshop ID#142 Manage and Monitor Autonomous Database
Added callouts to 2 screenshots in Lab 13: Public and Private Network Access in Autonomous Database

### CODE REVIEW

**Comment by hope-fisher** [comment]
@greenrick please resolve the existing conflict

**Comment by hope-fisher** [comment]
@greenrick are you able to use the command line to resolve the image conflict?

**Comment by greenrick** [comment]
@hope-fisher Hi, Hope. My GitHub page doesn't offer me the "Use the command line" link that you see on the screenshot you emailed me. So I didn't see a way to switch over to command line, nor was I comfortable using the command line for the first time to check out and check in as a method of resolving. However, I was able to find a GUI place on GitHub Desktop to resolve the mysterious "conflict" on the 2 screenshots I am attempting to update. I did a Resolve action on the 2 screenshots, in both cases choosing from the drop-down menu the new versions on my local "Main" instead of the production versions in "Upstream Main". Please see if the conflict appears to be resolved now, so that you can approve and merge my pull request. Thanks, Rick

**Comment by hope-fisher** [comment]
Thanks for sharing your solution!

**Review by hope-fisher — APPROVED** [review]

**Pull request merged**
